import { mkdir, readFile, writeFile } from "node:fs/promises"
import path from "node:path"
import { fileURLToPath } from "node:url"

const MAX_BUNDLE_BYTES = 300 * 1024

const scriptDir = path.dirname(fileURLToPath(import.meta.url))
const rootDir = path.resolve(scriptDir, "../..")
const entryFile = path.join(rootDir, "src/visualization/frontend/index.ts")
const cacheOutputFile = path.join(
  rootDir,
  ".cache/visualization/frontend-bundle.iife.js"
)
const generatedFile = path.join(
  rootDir,
  "src/visualization/frontendBundle.generated.ts"
)

const checkMode = process.argv.includes("--check")

const buildBundle = async (): Promise<string> => {
  await mkdir(path.dirname(cacheOutputFile), { recursive: true })

  const result = await Bun.build({
    entrypoints: [entryFile],
    outfile: cacheOutputFile,
    target: "browser",
    format: "iife",
    minify: true,
    sourcemap: "none"
  })

  if (!result.success) {
    throw new Error("Failed to build visualization frontend bundle")
  }

  const artifact = result.outputs[0]
  if (artifact === undefined) {
    throw new Error("Visualization frontend bundle build produced no outputs")
  }
  const text = await artifact.text()
  await writeFile(cacheOutputFile, text, "utf8")
  const bytes = Buffer.byteLength(text, "utf8")
  if (bytes > MAX_BUNDLE_BYTES) {
    throw new Error(
      `Visualization frontend bundle is ${bytes} bytes, which exceeds ${MAX_BUNDLE_BYTES} bytes.`
    )
  }

  return text
}

const toGeneratedSource = (bundleCode: string): string => {
  const bytes = Buffer.byteLength(bundleCode, "utf8")
  return `// This file is auto-generated by scripts/visualization/build-frontend-bundle.ts\n// Do not edit manually.\n\nexport const FRONTEND_BUNDLE_BYTES = ${bytes} as const\n\nexport const FRONTEND_BUNDLE = ${JSON.stringify(bundleCode)} as const\n`
}

const run = async (): Promise<void> => {
  const bundleCode = await buildBundle()
  const generatedSource = toGeneratedSource(bundleCode)

  if (checkMode) {
    const existing = await readFile(generatedFile, "utf8").catch(() => undefined)
    if (existing !== generatedSource) {
      throw new Error(
        "frontendBundle.generated.ts is out of date. Run `bun run build:visualization:bundle`."
      )
    }
    console.log("Visualization frontend bundle is up to date.")
    return
  }

  await mkdir(path.dirname(generatedFile), { recursive: true })
  await writeFile(generatedFile, generatedSource, "utf8")
  console.log(
    `Wrote ${path.relative(rootDir, generatedFile)} (${Buffer.byteLength(bundleCode, "utf8")} bytes).`
  )
}

run().catch((error) => {
  console.error(String(error))
  process.exitCode = 1
})
